C:\Users\missu3l\Desktop\React Prac\refractor\crsp-webui-router\src\data\home\api.test.ts:37
    _http_client.httpRequest.mockRejectedValueOnce(new Error('API error'));
                                                   ^

Error: API error
    at Object.<anonymous> (C:\Users\missu3l\Desktop\React Prac\refractor\crsp-webui-router\src\data\home\api.test.ts:36:56)
    at Promise.then.completed (C:\Users\missu3l\Desktop\React Prac\refractor\crsp-webui-router\node_modules\jest-circus\build\utils.js:391:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (C:\Users\missu3l\Desktop\React Prac\refractor\crsp-webui-router\node_modules\jest-circus\build\utils.js:316:10)
    at _callCircusTest (C:\Users\missu3l\Desktop\React Prac\refractor\crsp-webui-router\node_modules\jest-circus\build\run.js:218:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _runTest (C:\Users\missu3l\Desktop\React Prac\refractor\crsp-webui-router\node_modules\jest-circus\build\run.js:155:3)
    at _runTestsForDescribeBlock (C:\Users\missu3l\Desktop\React Prac\refractor\crsp-webui-router\node_modules\jest-circus\build\run.js:66:9)
    at _runTestsForDescribeBlock (C:\Users\missu3l\Desktop\React Prac\refractor\crsp-webui-router\node_modules\jest-circus\build\run.js:60:9)
    at run (C:\Users\missu3l\Desktop\React Prac\refractor\crsp-webui-router\node_modules\jest-circus\build\run.js:25:3) 
    at runAndTransformResultsToJestFormat (C:\Users\missu3l\Desktop\React Prac\refractor\crsp-webui-router\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapterInit.js:170:21)
    at jestAdapter (C:\Users\missu3l\Desktop\React Prac\refractor\crsp-webui-router\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapter.js:82:19)
    at runTestInternal (C:\Users\missu3l\Desktop\React Prac\refractor\crsp-webui-router\node_modules\jest-runner\build\runTest.js:389:16)
    at runTest (C:\Users\missu3l\Desktop\React Prac\refractor\crsp-webui-router\node_modules\jest-runner\build\runTest.js:475:34)
    at TestRunner.runTests (C:\Users\missu3l\Desktop\React Prac\refractor\crsp-webui-router\node_modules\jest-runner\build\index.js:101:12)
    at TestScheduler.scheduleTests (C:\Users\missu3l\Desktop\React Prac\refractor\crsp-webui-router\node_modules\@jest\core\build\TestScheduler.js:333:13)
    at runJest (C:\Users\missu3l\Desktop\React Prac\refractor\crsp-webui-router\node_modules\@jest\core\build\runJest.js:404:19)

Node.js v20.11.1

This error i am getting  for the below file 

import { getHomePageDetailsApi } from "./api";
import { httpRequest } from "../http_client";
import { HOME_DETAILS_URL } from "../endpoints";
import { mapAndThrowError } from "../api_error";

jest.mock('../http_client', () => ({
    httpRequest: jest.fn(),
}));

jest.mock('../api_error', () => ({
    mapAndThrowError: jest.fn(),
}));

describe('getHomePageDetailsApi', () => {
    test('should return home page details on successful API call', async () => {
        const mockResponseData = {
            deviceList: [],
            meshEnabledStatus: true,
            parentalControlList: [],
            routerStatus: 'Up',
            wifiList: [],
            timestamp: Date.now(),
        };

        (httpRequest as jest.Mock).mockResolvedValueOnce({
            readAsJson: jest.fn().mockResolvedValueOnce(mockResponseData),
        });

        const authToken = 'mockAuthToken';
        const result = await getHomePageDetailsApi(authToken);

        expect(result).toEqual(mockResponseData);
    });

    test('should handle error if API call fails', async () => {
        (httpRequest as jest.Mock).mockRejectedValueOnce(new Error('API error'));

        const authToken = 'mockAuthToken';
        await expect(getHomePageDetailsApi(authToken)).rejects.toThrow('API error');
        expect(mapAndThrowError).toHaveBeenCalled();
    });
});
